# BBO Capstone Analysis

This notebook provides a simple summary of query history and returned outputs from the Black-Box Optimisation (BBO) capstone project.

## Purpose
- organise query history by round and function
- track best and latest outputs
- examine changes across rounds
- support transparent and reproducible analysis of the optimisation process

In [2]:
import pandas as pd

## Example query history

The table below shows the structure used to record query points, function identifiers, and returned outputs across rounds.

In [3]:
data = [
    {"round": 1, "function": 1, "query": "0.100000-0.200000", "output": 0.12},
    {"round": 2, "function": 1, "query": "0.120000-0.250000", "output": 0.18},
    {"round": 3, "function": 1, "query": "0.130000-0.240000", "output": 0.16},
    {"round": 1, "function": 2, "query": "0.500000-0.400000", "output": -0.32},
    {"round": 2, "function": 2, "query": "0.550000-0.420000", "output": -0.20},
    {"round": 3, "function": 2, "query": "0.600000-0.450000", "output": -0.15},
]

df = pd.DataFrame(data)
df

   round  function              query  output
0      1         1  0.100000-0.200000    0.12
1      2         1  0.120000-0.250000    0.18
2      3         1  0.130000-0.240000    0.16
3      1         2  0.500000-0.400000   -0.32
4      2         2  0.550000-0.420000   -0.20
5      3         2  0.600000-0.450000   -0.15

In [3]:
summary = df.groupby("function").agg(
    rounds_recorded=("round", "count"),
    best_output=("output", "max"),
    latest_output=("output", "last"),
)
summary

          rounds_recorded  best_output  latest_output
function
1                       3         0.18           0.16
2                       3        -0.15          -0.15

In [4]:
df["change_from_previous"] = df.groupby("function")["output"].diff()
df

   round  function              query  output  change_from_previous
0      1         1  0.100000-0.200000    0.12                   NaN
1      2         1  0.120000-0.250000    0.18                  0.06
2      3         1  0.130000-0.240000    0.16                 -0.02
3      1         2  0.500000-0.400000   -0.32                   NaN
4      2         2  0.550000-0.420000   -0.20                  0.12
5      3         2  0.600000-0.450000   -0.15                  0.05

In [5]:
best_queries = df.loc[df.groupby("function")["output"].idxmax()].sort_values("function")
best_queries

   round  function              query  output  change_from_previous
1      2         1  0.120000-0.250000    0.18                  0.06
5      3         2  0.600000-0.450000   -0.15                  0.05

## Round-by-round changes

The next table shows how each function's output changed from one round to the next. This helps identify whether a function is improving steadily, plateauing, or behaving inconsistently.

In [6]:
df["change_from_previous"] = df.groupby("function")["output"].diff()
df

   round  function              query  output  change_from_previous
0      1         1  0.100000-0.200000    0.12                   NaN
1      2         1  0.120000-0.250000    0.18                  0.06
2      3         1  0.130000-0.240000    0.16                 -0.02
3      1         2  0.500000-0.400000   -0.32                   NaN
4      2         2  0.550000-0.420000   -0.20                  0.12
5      3         2  0.600000-0.450000   -0.15                  0.05

## Interpretation

This notebook is intended as a lightweight analysis tool rather than a full optimiser. It supports the capstone by making query history easier to inspect and compare across rounds.

Key ideas:
- repeated local gains may justify exploitation
- inconsistent results may justify exploration
- tracking changes over time supports better evidence-based query decisions